### ISSUE TITLE
Action 'Notify_the_team_of_the_request' failed

### ISSUE THREAD

**Issue by niknaks456** [MicrosoftDocs/powerapps-docs#1142]
Creating a request should be using the bot to create an update in my teams channel but getting the following error.

Microsoft.Azure.ProcessSimple.Data.Entities.Exceptions.ProcessSimpleDataException: The specified Teams flowbot adaptive card request is missing or invalid. The tracking Id is '{0}'. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: C. Path 'body[2].inlines[0].text', line 43, position 18.
   at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Microsoft.Azure.ProcessSimple.Data.Components.AdaptiveCards.AdaptiveCardBuilder.DeserializeAdaptiveCard(String serializedAdaptiveCard, RequestIdentity requestor) in X:\bt\1028462\repo\src\processsimple\Roles\ProcessSimple.Data\Components\AdaptiveCards\AdaptiveCardBuilder.cs:line 384
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ProcessSimple.Data.Components.AdaptiveCards.AdaptiveCardBuilder.DeserializeAdaptiveCard(String serializedAdaptiveCard, RequestIdentity requestor) in X:\bt\1028462\repo\src\processsimple\Roles\ProcessSimple.Data\Components\AdaptiveCards\AdaptiveCardBuilder.cs:line 392
   at Microsoft.Azure.ProcessSimple.Web.Common.Validation.BotAdaptiveCard(String card, RequestIdentity senderRequestIdentity) in X:\bt\1028462\repo\src\processsimple\Roles\ProcessSimple.Web\Common\Validation\BotValidation.cs:line 585

**Comment by phecke** [comment]
@niknaks456 
Is this about a documentation issue? If so, please provide a link to the topic page.

**Comment by mr-dang-msft** [comment]
Hi @niknaks456 @phecke 
This part means the adaptive card is missing some content:
`The specified Teams flowbot adaptive card request is missing or invalid.`

One test you can try:
- Create a Compose action ahead of the adaptive card. Copy the contents of the adaptive card here.
- Create a Terminate action after the Compose, but before the adaptive card.
- Re-run the flow so that you can see the contents of the adaptive card in the compose step. You might be missing content somewhere in the card that it is not appearing correctly.

(Please do not paste the output here)

**Comment by joostvdlinden** [comment]
I am getting the exact same error from within my Crisis Communication App workflow.
Any news so far on this?

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. This issue has been resolved in the latest app. Please feel free to reach out using the [issues link](https://aka.ms/crisis-communication-issues) for any additional issues.

**Comment by p-bojkowski** [comment]
@tapanm-MSFT the issue still exists :(

**Comment by tapanm-MSFT** [comment]
@p-bojkowski Please reach out using the [issues link](https://aka.ms/crisis-communication-issues) for further help with this issue.
