### ISSUE TITLE
how to associate multiple entities in one request? 

### ISSUE THREAD

**Issue by Flex-Xuan** [MicrosoftDocs/powerapps-docs#1232]
Hi there,

In the example '[Add a reference to a collection-valued navigation property](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api#add-a-reference-to-a-collection-valued-navigation-property)', the request body is :

> 

{  
"@odata.id":"[Organization URI]/api/data/v9.0/opportunities(00000000-0000-0000-0000-000000000001)"  
}  

it works fine, my question is how to associate multiple entities in one request?

say I have 2 or 3 opportunities related with one account? how to associate them in one request?
can this be done via web api?
Thanks
Flex

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e6444b56-0e82-a336-244d-67e4c3aeed05
* Version Independent ID: cb15df8b-5ef7-25b4-24cb-a48a4ec14e9d
* Content: [Associate and disassociate entities using the Web API (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api?view=dynamics-ce-odata-9#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/webapi/associate-disassociate-entities-using-web-api.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
I haven't tested this yet, but when I asked this question to one of the devs, they suggested that this would work:

PATCH [Organization URI]/api/data/v9.0/accounts(00000000-0000-0000-0000-000000000002)

{
“opportunity_customer_accounts@odata.bind”:[ 
"[Organization URI]/api/data/v9.0/opportunities(00000000-0000-0000-0000-000000000002)“, 
"[Organization URI]/api/data/v9.0/opportunities(00000000-0000-0000-0000-000000000003)"  
]
}

Once I have verified this, I'll add an example to the docs.

Let me know if this works for you or not.

**Comment by Flex-Xuan** [comment]
I tried this, but not working.
the response is :

> System.Exception: {"error":{"code":"0x0","message":"An error occurred while validating input parameters: System.NotImplementedException: Associate of 1:N navigation property with Create of Update is not supported in CRM
  at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyNestedProperty(Object entityResource, ODataNestedResourceInfoWrapper navigationLinkWrapper, IEdmStructuredTypeReference entityType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)","innererror":{"message":"An error occurred while validating input parameters: System.NotImplementedException: Associate of 1:N navigation property with Create of Update is not supported in CRM
  at Microsoft.Crm.Extensibility.CrmODataEntityDeserializer.ApplyNestedProperty(Object entityResource, ODataNestedResourceInfoWrapper navigationLinkWrapper, IEdmStructuredTypeReference entityType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ApplyNestedProperties(Object resource, ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.Deserialization.ODataResourceDeserializer.ReadResource(ODataResourceWrapper resourceWrapper, IEdmStructuredTypeReference structuredType, ODataDeserializerContext readContext)
  at System.Web.OData.Formatter.ODataMediaTypeFormatter.ReadFromStream(Type type, Stream readStream, HttpContent content, IFormatterLogger formatterLogger)","type":"Microsoft.Crm.CrmHttpException","stacktrace":" 
  at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.ValidateInputParameters(ModelStateDictionary controllerModelState)
  at Microsoft.Crm.Extensibility.OData.EntityController.PatchEntityImplementation(String& entityName, String key, EdmEntityObject entityDelta)
  at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)
  at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)
  at lambda_method(Closure , Object , Object[] )
  at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
  at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by JimDaly** [comment]
Thanks. Sorry to send you in the wrong direction.
This does not work today. I've created a workitem enable it. It is in our backlog.

**Comment by imranakram** [comment]
I'm hoping this would be available for onprem as well 🤞
