### ISSUE TITLE
Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by dzoech** [MicrosoftDocs/powerapps-docs#1311]
I'm implementing `IPlugin` and strictly following your example here:

```
var relationshipQueryCollection = new RelationshipQueryCollection();

var relatedTasks = new QueryExpression("task");
relatedTasks.ColumnSet = new ColumnSet("subject", "description");
var taskRelationship = new Relationship("Account_Tasks");
relationshipQueryCollection.Add(taskRelationship, relatedTasks);

var relatedContacts = new QueryExpression("contact");
relatedContacts.ColumnSet = new ColumnSet("fullname", "emailaddress1");
var contactRelationship = new Relationship("account_primary_contact");
relationshipQueryCollection.Add(contactRelationship, relatedContacts);

var request = new RetrieveRequest()
{
    ColumnSet = new ColumnSet(true),
    RelatedEntitiesQuery = relationshipQueryCollection,
    Target = new EntityReference("account", Guid.Parse("my guid ..."))
};

RetrieveResponse response = (RetrieveResponse)organizationService.Execute(request);
```

But `organizationService.Execute(request)` throws the following exception:

```
Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at PluginProfiler.Plugins.ServiceWrappers.ProxyTypesWrapper.ConvertToEarlyBound(Entity value)
   at PluginProfiler.Plugins.ServiceWrappers.ProxyTypesWrapper.ConvertToEarlyBound(Object value)
   at PluginProfiler.Plugins.PartialTrustSerializer.SpecialTypeSerializationSurrogate.GetDeserializedObject(Object obj, Type targetType)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.CollectionDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, String name, String ns)
   at System.Runtime.Serialization.ClassDataContract.ReadXmlValue(XmlReaderDelegator xmlReader, XmlObjectSerializerReadContext context)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserializeWithSurrogate(XmlReaderDelegator xmlReader, Type declaredType, DataContract surrogateDataContract, String name, String ns)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(Stream stream)
   at PluginProfiler.Plugins.PartialTrustSerializer.Deserialize(Type type, Byte[] value, Assembly proxyTypesAssembly)
   at PluginProfiler.ProfilerSharedUtility.Deserialize(Type type, String value, Assembly proxyTypesAssembly)
   at PluginProfiler.Library.ProfilerContextAppDomainOrganizationService.DeserializeResponse(Tuple`2 serializedValue)
   at PluginProfiler.Library.ProfilerContextAppDomainOrganizationService.Execute(OrganizationRequest request)
   at D365PackageProject.Services.RelationshipResolver`1.ExecuteQuery(TEntity entity) in C:\Users\dzoech\git-repos\plm\src\D365PackageProject\D365PackageProject\Services\RelationshipResolver.cs:line 100
   at D365PackageProject.CustomerProductRelationshipValidator.Execute(IServiceProvider serviceProvider) in C:\Users\dzoech\git-repos\plm\src\D365PackageProject\D365PackageProject\CustomerProductRelationshipValidator.cs:line 43
```

I don't manipulate any iterator or IEnumerable myself. Can you reproduce this issue or could you please tell me what I'm missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03834551-94e2-b4c7-f1fb-4536d491b1bb
* Version Independent ID: f614b262-d535-f8b3-2e48-39edbac28f2b
* Content: [Retrieve an entity using the Organization Service (Common Data Service) - Power Apps](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/org-service/entity-operations-retrieve#feedback)
* Content Source: [powerapps-docs/developer/common-data-service/org-service/entity-operations-retrieve.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/developer/common-data-service/org-service/entity-operations-retrieve.md)
* Service: **powerapps**
* GitHub Login: @JimDaly
* Microsoft Alias: **jdaly**

**Comment by JimDaly** [comment]
Does it work if you are not using Plug-in Profiler?

**Comment by dzoech** [comment]
Thanks for the quick reply @JimDaly 

Yes, it seems like it works when I disable the profiling.

**Comment by dzoech** [comment]
Might it be possible to work around this issue by using fetch XML instead of query expressions?

**Comment by JimDaly** [comment]
IDK, you shouldn't have to do that.

If you haven't updated the Plug-in Registration tool recently, I would suggest you get the latest version.
You may also need to uninstall and re-install the plug-in profiler solution.
If neither of these work, it looks like an issue with the plug-in profiler.

Let me know what you find out.

**Comment by dzoech** [comment]
I just installed the plugin registration tool about 10 days ago from the latest nuget package. I will have a look tomorrow if there is an update available.

> You may also need to uninstall and re-install the plug-in profiler solution.

I think I can't follow you here. What does the 'profiler solution' refere to? Do you mean to unregister and re-register the custom plugin assembly using the tool? I don't have a profiler.sln...

**Comment by JimDaly** [comment]
You may want to reinstall even so... There have been reports of some issues recently.
There is a row of commands in the tab. When profiler is installed, there will be an **Uninstall Profiler** option between View and Debug.
If it isn't installed, it will say **Install Profiler**

You don't need the solution file, the PRT will do it for you.

**Comment by dzoech** [comment]
So, I now reinstalled the Plugin Registration tool as described in your [docs](https://docs.microsoft.com/en-us/dynamics365/customerengagement/on-premises/developer/download-tools-nuget#download-tools-using-powershell). Before, I uninstalled the Profiler and now re-installed it.

This didn't fix the problem. The exception didn't change and it is still working without the profiler.

**Comment by JimDaly** [comment]
Thanks for trying. I'm going to send this to the team that owns the plug-in profiler as an issue they should look into. They may have a workaround or can identify what needs to be changed.

**Comment by dzoech** [comment]
Thank you. Is there a way to follow the issue or receive an update once its fixed?

**Comment by dzoech** [comment]
Any updates on this one @JimDaly ?

**Comment by JimDaly** [comment]
These issues are for documentation feedback.
What you are describing is a problem with the plug-in profiler. I'm fine with providing some basic support in this space. I appreciate you going through the steps I asked. I shared this issue with the PRT team to make them aware, but this isn't a problem that can be solved through documentation. It is out of scope for this channel.

If this is blocking you, I recommend you open a support ticket. Issues raised by support that are known to be impacting customers get more attention than emails from me. 
You can send them the link to this issue since you have described the behavior.

I will also ping the tools team about this, but I can't guarantee a response.

Closing this as a documentation issue.
