### ISSUE TITLE
Cannot Load Data Model

### ISSUE THREAD

**Issue by gjross14** [MicrosoftDocs/powerapps-docs#1661]
With latest version of PowerBI Desktop 2.84.701.0, the data model cannot load.

Feedback Type:
Frown (Error)

Timestamp:
2020-08-14T09:23:46.1482057Z

Local Time:
2020-08-14T10:23:46.1482057+01:00

Session ID:
450d9bb6-8c15-48c4-a157-132fe4d893ef

Release:
August 2020

Product Version:
2.84.701.0 (20.08) (x64)

Error Message:
We couldn't connect to your DirectQuery data source or internal model. Double-check that your server and database names are correct, and that you have permission to access them.

Error Message Detail:
Index was outside the bounds of the array.. The exception was raised by the IDataReader interface. Please review the error message and provider documentation for further information and corrective action.

Stack Trace:
Microsoft.PowerBI.ReportingServicesHost.CannotRetrieveModelException: An error occurred while loading the model. Verify that the connection information is correct and that you have permissions to access the data source. ---> Microsoft.PowerBI.DataExtension.Contracts.DataExtensionException: Failed to get CSDL. ---> MsolapWrapper.MsolapWrapperException: Failure encountered while getting schema
   at MsolapWrapper.Utils.ThrowErrorIfHrFailed(Int32 hr, String message)
   at MsolapWrapper.CDbSchemaRowsetWrapper.ExecuteSchemaRowset(Guid schema, Object[] restrictions, PropertySetCollection propSets)
   at MsolapWrapper.SchemaCommand.ExecuteReader(Guid schema, Object[] restrictions)
   at MsolapWrapper.SchemaCommand.GetModelMetadata(Object[] restrictions)
   at Microsoft.PowerBI.DataExtension.Msolap.SchemaCommand.GetModelMetadata(String catalogName, String perspectiveName, String supportedVersion)
   --- End of inner exception stack trace ---
   at Microsoft.PowerBI.DataExtension.Msolap.SchemaCommand.GetModelMetadata(String catalogName, String perspectiveName, String supportedVersion)
   at Microsoft.PowerBI.ReportingServicesHost.LocalReportProcessingHost.ExecuteSchemaCommand[T](ExploreHostDataSourceInfo dataSourceInfo, IDbConnectionPool connectionPool, IConnectionFactory connectionFactory, IConnectionUserImpersonator connectionUserImpersonator, QueryExecutionOptionsBase queryExecutionOptions, ITelemetryService telemetryService, Func`2 action, String failTelemetryMessage, ServiceErrorStatusCode statusCode, ExploreBaseEvent exploreEvent)
   --- End of inner exception stack trace ---
   at Microsoft.PowerBI.ReportingServicesHost.LocalReportProcessingHost.ExecuteSchemaCommand[T](ExploreHostDataSourceInfo dataSourceInfo, IDbConnectionPool connectionPool, IConnectionFactory connectionFactory, IConnectionUserImpersonator connectionUserImpersonator, QueryExecutionOptionsBase queryExecutionOptions, ITelemetryService telemetryService, Func`2 action, String failTelemetryMessage, ServiceErrorStatusCode statusCode, ExploreBaseEvent exploreEvent)
   at Microsoft.PowerBI.ReportingServicesHost.LocalReportProcessingHost.<>c__DisplayClass9_0.<GetModelMetadata>b__1(ExploreBaseEvent timedEvent)
   at Microsoft.PowerBI.ReportingServicesHost.ExploreTelemetryService.<>c__DisplayClass4_0`1.<RunInActivity>b__0(ExploreBaseEvent activity)
   at Microsoft.PowerBI.ReportingServicesHost.ExploreTelemetryService.RunInActivity(String activityName, Action`1 action)
   at Microsoft.PowerBI.ReportingServicesHost.ExploreTelemetryService.RunInActivity[T](String activityName, Func`2 action)
   at Microsoft.PowerBI.ReportingServicesHost.LocalReportProcessingHost.GetModelMetadata(ExploreHostDataSourceInfo dataSourceInfo, IDbConnectionPool connectionPool, IConnectionFactory connectionFactory, String modelMetadataVersion, QueryExecutionOptionsBase queryExecutionOptions, IConnectionUserImpersonator connectionUserImpersonator, ITelemetryService telemetryService)
   at Microsoft.PowerBI.ReportingServicesHost.ReportingSession.GetModel(String dataSourceName, String modelMetadataVersion)
   at Microsoft.PowerBI.ReportingServicesHost.ReportingSession.GetModelAsStream(String dataSourceName, String modelMetadataVersion)
   at Microsoft.PowerBI.ReportingServicesHost.ReportingSession.GetConceptualSchema(String modelMetadataVersion, ParseConceptualSchema parse, ModelDaxCapabilities& capabilities)
   at Microsoft.PowerBI.ExploreHost.Utils.ExploreHostUtils.GetConceptualSchemaImpl(IPowerViewHandler powerViewHandler, String databaseID, String maxModelMetadataVersion, ModelDaxCapabilities& capabilities)
   at Microsoft.PowerBI.ExploreHost.Utils.ExploreHostUtils.HandleModelRetrievalExceptions[T](Func`1 wrappedCall, String databaseID, ServiceErrorStatusCode statusCode, FeatureSwitches featureSwitches)
   at Microsoft.PowerBI.ExploreHost.Utils.ExploreHostUtils.GetConceptualSchemaAndHandleExceptions(IPowerViewHandler powerViewHandler, String databaseID, String maxModelMetadataVersion, ModelDaxCapabilities& daxCapabilities)
   at Microsoft.PowerBI.ExploreHost.Utils.ExploreHostUtils.<>c__DisplayClass26_0.<TryGetConceptualSchema>b__0()
   at Microsoft.PowerBI.ExploreHost.Utils.ExploreHostUtils.TryGetStructureImpl[T](Int64 modelID, ServiceErrorExtractor extractor, Func`1 getStructure, Func`2 validateStructure, T& structure, ServiceError& serviceError)

Invocation Stack Trace:
   at Microsoft.Mashup.Host.Document.ExceptionExtensions.GetCurrentInvocationStackTrace()
   at Microsoft.Mashup.Client.UI.Shared.StackTraceInfo..ctor(String exceptionStackTrace, String invocationStackTrace, String exceptionMessage)
   at Microsoft.PowerBI.Client.Windows.ErrorHostService.GetErrorDetails(ShowErrorDialogArgs args)
   at Microsoft.PowerBI.Client.Windows.ErrorHostService.<>c__DisplayClass2_0.<<ShowErrorDialog>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PowerBI.Client.Windows.ErrorHostService.<>c__DisplayClass2_0.<ShowErrorDialog>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass1_0`1.<SendAndMarshalExceptions>b__0()
   at Microsoft.Mashup.Host.Document.SynchronizationContextExtensions.<>c__DisplayClass0_1.<SendAndMarshalExceptions>b__0(Object null)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.Mashup.Client.UI.Shared.Ux.WindowService.ShowStatusDialog(LocalizedString message, Action cancelCallback, Nullable`1 showDelayInMs)
   at Microsoft.PowerBI.Client.Windows.BusyHelper.ShowBusyDialog(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Form.ShowDialog(IWin32Window owner)
   at Microsoft.Mashup.Client.UI.Windows.DialogWindowBase.ShowModal(IWindowHandle windowHandle)
   at Microsoft.Mashup.Client.UI.Shared.WebDialogs.WebDialog.<>n__0(IWindowHandle owner)
   at Microsoft.Mashup.Client.UI.Shared.WindowManager.ShowModal[T](T dialog, Func`1 showModalFunction)
   at Microsoft.PowerBI.Client.Program.<>c__DisplayClass1_0.<Main>b__1()
   at Microsoft.PowerBI.Client.Windows.IExceptionHandlerExtensions.<>c__DisplayClass3_0.<HandleExceptionsWithNestedTasks>b__0()
   at Microsoft.Mashup.Host.Document.ExceptionHandlerExtensions.HandleExceptions(IExceptionHandler exceptionHandler, Action action)
   at Microsoft.PowerBI.Client.Program.Main(String[] args)

OS Version:
Microsoft Windows NT 10.0.19041.0 (x64 en-GB)

CLR Version:
4.7 or later [Release Number = 528372]

Peak Virtual Memory:
38.1 GB

Private Memory:
620 MB

Peak Working Set:
836 MB

IE Version:
11.450.19041.0

User ID:
1541be57-342b-435e-998c-4353f1c55f83

Workbook Package Info:
1* - en-GB, Query Groups: 0, fastCombine: Disabled, runBackgroundAnalysis: True.

Telemetry Enabled:
True

Snapshot Trace Logs:
C:\Users\xxx\AppData\Local\Microsoft\Power BI Desktop\FrownSnapShot538453039.zip

Model Default Mode:
DirectQuery

Model Version:
PowerBI_V1

Is Report V3 Models Enabled:
False

Performance Trace Logs:
C:\Users\xxx\AppData\Local\Microsoft\Power BI Desktop\PerformanceTraces.zip

Enabled Preview Features:
PBI_NewWebTableInference

Disabled Preview Features:
PBI_shapeMapVisualEnabled
PBI_SpanishLinguisticsEnabled
PBI_ImportTextByExample
PBI_qnaLiveConnect
PBI_inlineExplore
PBI_v3ModelsPreview
PBI_dataSearchCuration
PBI_azureMapVisual
PBI_dataPointLassoSelect

Disabled DirectQuery Options:
TreatHanaAsRelationalSource

Cloud:
GlobalCloud

DPI Scale:
200%

Supported Services:
Power BI

Formulas:

section Section1;

shared account = let
    Source = Sql.Databases("orgxxc.crm11.dynamics.com,5558"),
    orgxxxc = Source{[Name="orgxxxc"]}[Data],
    dbo_account = orgxxxc{[Schema="dbo",Item="account"]}[Data]
in
    dbo_account;

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c3d27f9-66bc-5cd2-d8b5-9defc8eddfb0
* Version Independent ID: c45841f0-1488-8c30-8a7c-3a522ec63266
* Content: [View entity data in Power BI Desktop (Preview) - Power Apps](https://docs.microsoft.com/en-gb/powerapps/maker/common-data-service/view-entity-data-power-bi)
* Content Source: [powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/view-entity-data-power-bi.md)
* Service: **powerapps**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by Mattp123** [comment]
@gjross14 - If this is still an issue contact Support. More information: https://powerapps.microsoft.com/support/ 

Closing this issue.
