### ISSUE TITLE
Having new Flow Connection References in Solution leads to Error in Solution Packager

### ISSUE THREAD

**Issue by bananamufu** [MicrosoftDocs/powerapps-docs#1777]
Testing out the preview feature Connection References.

In Azure DevOps, Power Platform Pack Solution Task or 3rd party extension that also uses Solution Packager leads to "Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 11, position 2" error.

Same Solution works fine if you remove the new Connection References.

Error Log:
`
    ##[debug]Get-Var: allowDelete = Yes
    ##[debug]Get-Var: allowWrite = Yes
    ##[debug]Attempting to get env variable: Env:\PowerPlatformTools_Microsoft_CrmSdk_CoreTools)
    ##[debug]NuGet Package Root Path: D:\agent\_work\10\_t\PA_BT\Microsoft.CrmSdk.CoreTools.9.1.0.49
    ##[debug]SolutionPackager.exe found: D:\agent\_work\10\_t\PA_BT\Microsoft.CrmSdk.CoreTools.9.1.0.49\content\bin\coretools\SolutionPackager.exe
    "D:\agent\_work\10\_t\PA_BT\Microsoft.CrmSdk.CoreTools.9.1.0.49\content\bin\coretools\SolutionPackager.exe" /allowDelete:Yes /action:Pack /zipFile:"D:\agent\_work\10\b" /allowWrite:Yes /folder:"D:\agent\_work\10\s\bms_batch_invoices" /packagetype:Unmanaged 
    SolutionPackger CRM Solution Packaging Tool [Version 9.1.0.52]
    © 2017 Microsoft Corporation.  All rights reserved

    Packing D:\agent\_work\10\s\bms_batch_invoices to D:\agent\_work\10\b

    Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 11, position 2.
    SolutionPackager: Exception thrown: System.Xml.XmlException: Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 11, position 2.
       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
       at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
       at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
       at System.Xml.XmlTextReaderImpl.ParseElement()
       at System.Xml.XmlTextReaderImpl.ParseElementContent()
       at System.Xml.XmlTextReaderImpl.Read()
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
       at Microsoft.Crm.Tools.SolutionPackager.Helper.LoadSolutionInformation(Stream solutionXml, Context context)
       at Microsoft.Crm.Tools.SolutionPackager.DiskReader.Load()
       at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run(IPackageReader reader, IPackageWriter writer)
       at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run()
       at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args), returning error code '1'
    ##[debug]Exit code: 1
    ##[debug]Leaving D:\agent\_work\_tasks\PowerPlatformPackSolution_769929ed-e421-451b-8255-21a8d9d9d3f9\0.0.13\PackSolution.ps1.
    ##[debug]Caught exception from task script.
    ##[debug]Error record:
    ##[debug]Invoke-SolutionPackager : SolutionPackager failed: 1
    ##[debug]At D:\agent\_work\_tasks\PowerPlatformPackSolution_769929ed-e421-451b-8255-21a8d9d9d3f9\0.0.13\PackSolution.ps1:26 char:9
    ##[debug]+         Invoke-SolutionPackager @SolutionPackagerParms
    ##[debug]+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ##[debug]    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    ##[debug]    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-SolutionPackager

`
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6296f1c9-8505-cca0-3b3c-50fbf988d663
* Version Independent ID: a5bf3054-8a46-39d0-9c3f-3270080d8fbc
* Content: [Connection references in solutions - Power Apps](https://docs.microsoft.com/en-us/powerapps/maker/common-data-service/create-connection-reference)
* Content Source: [powerapps-docs/maker/common-data-service/create-connection-reference.md](https://github.com/MicrosoftDocs/powerapps-docs/blob/live/powerapps-docs/maker/common-data-service/create-connection-reference.md)
* Service: **powerapps**
* GitHub Login: @caburk
* Microsoft Alias: **caburk**

**Comment by caburk** [comment]
This does not appear related to connection references. It looks like bad XML within the solution.xml file and therefore the XML reader is throwing an error. Please try removing the '<' character in this file.
