### ISSUE TITLE
pac paportal download error "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by ryanmichaeljames** [MicrosoftDocs/powerapps-docs#3911]
I'm trying to download the portal with the `pac paportal download` command but it is throwing the following error when **Updating manifect...**

![image](https://user-images.githubusercontent.com/16380903/208808452-a7a29070-2476-4522-9188-c6851d6c73e8.png)

The log file contains the following error:

```
2022-12-21 02:36:03.6306|INFO|bolt.module.paportal.PortalDataExporter|Parsing adx_contentsnippet [Search-Title]
2022-12-21 02:36:03.6477|INFO|bolt.cli.CommandProcessor|EndExecutingVerb (Success: False, Execution Time(ms): 842)
2022-12-21 02:36:03.6861|FATAL|bolt.cli.Session|The given key was not present in the dictionary.
2022-12-21 02:36:03.6861|ERROR|bolt.cli.Session|   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at bolt.module.paportal.core.PortalDataManifestProvider.UpsertManifestEntry(String entityLogicalName, IDictionary`2 record)
   at bolt.module.paportal.core.PortalDataManifestProvider.<>c__DisplayClass18_0.<GeneratePortalManifest>b__0(XmlNode xn)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at bolt.module.paportal.core.PortalDataManifestProvider.GeneratePortalManifest()
   at bolt.module.paportal.PortalDataExporter.DownloadData()
   at bolt.module.paportal.verbs.PAPortalDownloadVerb.Execute(IContext context, Command command)
   at bolt.cli.Verb.<>c__DisplayClass7_0.<<RunVerbExecutor>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at bolt.cli.Verb.RunVerbExecutor(IProcessCommandContext context, Command command)
   at bolt.cli.Verb.Execute(IProcessCommandContext context, Command command, Queue`1 nextCommands)
   at bolt.cli.CommandProcessor.ProcessCommands(Queue`1 commands, IVerbFactory factory)
   at bolt.cli.CommandProcessor.LaunchCommand(IReadOnlyList`1 args, UserHelpText userHelpText, Boolean isNonInteractiveModeEnabled)
   at bolt.cli.Session.Run(ProgramArguments args)
2022-12-21 02:36:04.0018|INFO|bolt.cli.Session|End session. (ResponseCode: 500)
```

**Comment by JimDaly** [comment]
@ryanmichaeljames 
Issues in this repo must be about the documentation. Looks like you are reporting an issue with the product.
I recommend you contact technical support for product issues.
@kkanakas, if there is any way we can update the documentation to prevent this issue, please re-open this.
